[package]
name = "stakex-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.stakex]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.6"
default-features = false
